# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy to internal sharing."
  lane :internal do
      firebase_app_distribution(
        app: "1:217323738064:android:69b0e7b3ca4a8e2f6d1fd5",
        android_artifact_type: "aab",
        android_artifact_path: "./app/build/outputs/bundle/betaRelease/app-beta-release.aab",
        service_credentials_file: ENV["GOOGLE_APP_CREDENTIALS"],
      )
      upload_to_play_store(
          json_key: ENV["ANDROID_JSON_KEY_FILE"],
          track: 'internal',
          skip_upload_images: 'true',
          skip_upload_screenshots: 'true',
          skip_upload_changelogs: 'true',
          aab: "./app/build/outputs/bundle/betaRelease/app-beta-release.aab"
      )
    end

  desc "Submit a new Beta Build and release."
  lane :beta do
      firebase_app_distribution(
        app: "1:217323738064:android:69b0e7b3ca4a8e2f6d1fd5",
        android_artifact_type: "aab",
        android_artifact_path: "./app/build/outputs/bundle/betaRelease/app-beta-release.aab",
        service_credentials_file: ENV["GOOGLE_APP_CREDENTIALS"],
      )
      upload_to_play_store(
          json_key: ENV["ANDROID_JSON_KEY_FILE"],
          track: 'beta',
          skip_upload_images: 'true',
          skip_upload_screenshots: 'true',
          skip_upload_changelogs: 'true',
          aab: "./app/build/outputs/bundle/betaRelease/app-beta-release.aab",
          rollout: 0.1
      )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
      upload_to_play_store(
          json_key: ENV["ANDROID_JSON_KEY_FILE"],
          track: 'production',
          skip_upload_images: 'true',
          skip_upload_screenshots: 'true',
          skip_upload_changelogs: 'true',
          aab: "./app/build/outputs/bundle/fullRelease/app-full-release.aab",
          rollout: 0.1
      )
  end
end
