# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy to internal sharing."
  lane :internal do
      gradle(
        task: 'bundle', 
        flavor: 'beta', 
        build_type: 'Release',
        properties: {
          "android.injected.signing.store.file" => ENV["KEYSTORE_FILE"],
          "android.injected.signing.store.password" => ENV["STORE_PASSWORD"],
          "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
          "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
        }
      )
      upload_to_play_store(
          json_key: ENV["ANDROID_JSON_KEY_FILE"],
          track: 'internal',
          skip_upload_images: 'true',
          skip_upload_screenshots: 'true'
      )
    end

  desc "Submit a new Beta Build and release."
  lane :beta do
    gradle(task: 'bundle', flavor: 'beta', build_type: 'Release')
    upload_to_play_store(
        json_key: ENV["ANDROID_JSON_KEY_FILE"],
        track: 'beta',
        skip_upload_images: 'true',
        skip_upload_screenshots: 'true'
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do

    gradle(task: 'bundle', flavor: 'full', build_type: 'Release')
    rollout = prompt(
      text: "Rollout: "
    )
    upload_to_play_store(
        json_key: ENV["ANDROID_JSON_KEY_FILE"],
        track: 'production',
        rollout: rollout,
        skip_upload_images: 'true',
        skip_upload_screenshots: 'true'
    )
  end
end
