package com.austinhodak.tarkovapi

import com.austinhodak.tarkovapi.room.models.Item
import com.austinhodak.tarkovapi.room.models.toItem
import org.json.JSONObject

object TestUtil {
    fun createItem(): Item {
        return toItem(
            JSONObject("{\"_id\":\"590c657e86f77412b013051d\",\"_name\":\"AMK_Grizzly\",\"_parent\":\"5448f39d4bdc2d0a728b4568\",\"_type\":\"Item\",\"_props\":{\"Name\":\"Grizzly medical kit\",\"ShortName\":\"Grizzly\",\"Description\":\"Sportsman Series Grizzly Medical Kit is considered one of the best first aid kits. It contains everything necessary to provide immediate medical care in extreme conditions.\",\"Weight\":1.6,\"BackgroundColor\":\"orange\",\"Width\":2,\"Height\":2,\"StackMaxSize\":1,\"Rarity\":\"Superrare\",\"SpawnChance\":3,\"CreditsPrice\":21901,\"ItemSound\":\"med_medkit\",\"Prefab\":{\"path\":\"assets\\/content\\/weapons\\/usable_items\\/item_meds_grizly\\/item_grizzly_loot.bundle\",\"rcid\":\"\"},\"UsePrefab\":{\"path\":\"assets\\/content\\/weapons\\/usable_items\\/item_meds_grizly\\/item_meds_grizly_container.bundle\",\"rcid\":\"\"},\"StackObjectsCount\":1,\"NotShownInSlot\":false,\"ExaminedByDefault\":false,\"ExamineTime\":1,\"IsUndiscardable\":false,\"IsUnsaleable\":false,\"IsUnbuyable\":false,\"IsUngivable\":false,\"IsLockedafterEquip\":false,\"QuestItem\":false,\"LootExperience\":40,\"ExamineExperience\":10,\"HideEntrails\":false,\"RepairCost\":0,\"RepairSpeed\":0,\"ExtraSizeLeft\":0,\"ExtraSizeRight\":0,\"ExtraSizeUp\":0,\"ExtraSizeDown\":0,\"ExtraSizeForceAdd\":false,\"MergesWithChildren\":false,\"CanSellOnRagfair\":true,\"CanRequireOnRagfair\":true,\"ConflictingItems\":[],\"FixedPrice\":false,\"Unlootable\":false,\"UnlootableFromSlot\":\"FirstPrimaryWeapon\",\"UnlootableFromSide\":[],\"ChangePriceCoef\":1,\"AllowSpawnOnLocations\":[],\"SendToClient\":false,\"AnimationVariantsNumber\":2,\"DiscardingBlock\":false,\"RagFairCommissionModifier\":1,\"IsAlwaysAvailableForInsurance\":false,\"medUseTime\":5,\"medEffectType\":\"duringUse\",\"MaxHpResource\":1800,\"hpResourceRate\":175,\"StimulatorBuffs\":\"\",\"effects_health\":[],\"effects_damage\":{\"LightBleeding\":{\"delay\":0,\"duration\":0,\"fadeOut\":0,\"cost\":40},\"HeavyBleeding\":{\"delay\":0,\"duration\":0,\"fadeOut\":0,\"cost\":130},\"Fracture\":{\"delay\":0,\"duration\":0,\"fadeOut\":0,\"cost\":50},\"Contusion\":{\"delay\":0,\"duration\":0,\"fadeOut\":0,\"cost\":0},\"RadExposure\":{\"delay\":0,\"duration\":0,\"fadeOut\":0,\"cost\":0}}},\"_proto\":\"544fb45d4bdc2dee738b4568\"}")
        )
    }
}